### ISSUE TITLE
Error on parsing options with comments

### ISSUE THREAD

**Issue by thepabloaguilar** [pyscaffold/configupdater#14]
## Error on parsing options with comments

Thanks for your work in this lib, I've just found some errors when we have comments in our options. See the example bellow:

__setup.cfg__:
```ini
[flake8]

exclude =
  # Trash and cache:
  .git
  __pycache__
  .venv
  .eggs
  *.egg
  temp
  # Bad code that I write to test things:
  ex.py
```

```python
>>> from configupdater import ConfigUpdater
>>> updater = ConfigUpdater()
>>> updater.read('/lambdas/setup.cfg')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.cache/pypoetry/virtualenvs/lambdas-swHUnyqi-py3.9/lib/python3.9/site-packages/configupdater/configupdater.py", line 618, in read
    self._read(fp, filename)
  File "/.cache/pypoetry/virtualenvs/lambdas-swHUnyqi-py3.9/lib/python3.9/site-packages/configupdater/configupdater.py", line 826, in _read
    raise e
configparser.ParsingError: Source contains parsing errors: '/lambdas/setup.cfg'
	[line 10]: '  lambdas/contrib/mypy/*\n'
	[line 39]: '  .git\n'
	[line 40]: '  __pycache__\n'
	[line 41]: '  .venv\n'
	[line 42]: '  .eggs\n'
	[line 43]: '  *.egg\n'
	[line 44]: '  temp\n'
	[line 46]: '  ex.py\n'
```

---

Other error I've found, sometimes we didn't get the `ParsingError` with comments but our options is parsed wrongly. See the example below:

__setup.cfg__:
```ini
[flake8]

exclude =
  .git
  __pycache__
  .venv
  .eggs
  *.egg
  temp
  ex.py

per-file-ignores =
  # Disable imports in `__init__.py`:
  lambdas/__init__.py: WPS226, WPS413
  lambdas/contrib/mypy/lambdas_plugin.py: WPS437
  # There are multiple assert's in tests:
  tests/*.py: S101, WPS226, WPS432, WPS436, WPS450
  # We need to write tests to our private class:
  tests/test_math_expression/*.py: S101, WPS432, WPS450
```

```python
>>> from configupdater import ConfigUpdater
>>>
>>> updater = ConfigUpdater()
>>> updater.read('/Projects/lambdas/setup.cfg')
>>>
>>> per_file_ignores = updater['flake8']['per-file-ignores']
>>> per_file_ignores
<Option: per-file-ignores = >
>>> per_file_ignores.lines
['per-file-ignores =\n']
>>>
>>> # While `exclude` is fine
>>>
>>> exclude = updater['flake8']['exclude']
>>> exclude
<Option: exclude = 
.git
__pycache__
.venv
.eggs
*.egg
temp
ex.py>
>>> exclude.lines
['exclude =\n', '  .git\n', '  __pycache__\n', '  .venv\n', '  .eggs\n', '  *.egg\n', '  temp\n', '  ex.py\n']
```

**Please provide any additional information below.**

Refs https://github.com/andreoliwa/nitpick/issues/296

## Versions and main components

* ConfigUpdater Version: 1.1.3
* Python Version: 3.9
* Operating system: Linux
* How did you install ConfigUpdater: pip

**Comment by thepabloaguilar** [comment]
`configparser` works correctly:
```python
>>> from configparser import ConfigParser
>>> parser = ConfigParser()

>>> parser.read(/Projects/lambdas/setup.cfg')
['/home/pabloaguilar/Projects/lambdas/setup.cfg']
>>> parser.sections()
['coverage:run', 'flake8', 'tool:pytest', 'isort', 'mypy', 'doc8']

>>> parser['flake8']['exclude']
'\n.git\n__pycache__\n.venv\n.eggs\n*.egg\ntemp\nex.py'
>>> parser['flake8']['per-file-ignores']
'\nlambdas/__init__.py: WPS226, WPS413\nlambdas/contrib/mypy/lambdas_plugin.py: WPS437\ntests/*.py: S101, WPS226, WPS432, WPS436, WPS450\ntests/test_math_expression/*.py: S101, WPS432, WPS450'
```

**Comment by FlorianWilhelm** [comment]
Thanks for reporting this bug @thepabloaguilar. Sadly, it's a tricky one. The reason is that you are using comments within a multi-line option. The current concept of configupdater supports comments between sections and between options but not comments within a value. A fix would be to just have the comment within the value and not treating it as a special object. Would that work for you?

**Comment by FlorianWilhelm** [comment]
@thepabloaguilar, could you please test the branch `multiline-comment` and check if it works for your use-case? If it does I would release a new version 2.0.

**Comment by thepabloaguilar** [comment]
Thanks a lot for your time!!
I'm not sure if leaving the comments as an option value is a great thing!! 🤔 
What about giving two properties, `lines` and `raw_lines` (that will include the comments)?

Btw, it'll be great to hear @andreoliwa. He is the guy behind `nitpick` that uses `configupdater`

**Comment by FlorianWilhelm** [comment]
The `lines` attribute was never really intended to be used directly and I am even considering removing it thus. You should rather use `.value` which gives you in case of `updater["flake8"]["per-file-ignores"].value`:
```
\n# Disable imports in `__init__.py`:
\nlambdas/__init__.py: WPS226, WPS413"
\nlambdas/contrib/mypy/lambdas_plugin.py: WPS437
\n# There are multiple assert's in tests:
\ntests/*.py: S101, WPS226, WPS432, WPS436, WPS450
\n# We need to write tests to our private class:
\ntests/test_math_expression/*.py: S101, WPS432, WPS450
```
in contrast to `parser["flake8"]["per-file-ignores"]`: 
```
\nlambdas/__init__.py: WPS226, WPS413
\nlambdas/contrib/mypy/lambdas_plugin.py: WPS437
\ntests/*.py: S101, WPS226, WPS432, WPS436, WPS450
\ntests/test_math_expression/*.py: S101, WPS432, WPS450
```
So the return type of `value` is always a string. One could create a function `values()` (note the plural s), which replaces `lines` and always returns a list of strings. This list of strings could be the original `value` stripped and split by `\n`. With `values(comments=False)` one could even filter out all strings in this list starting with a comment symbol. I am just not sure if this functionality really should be inside of configupdater. It would be more about reading and using the values of a configuration rather than updating. Also, configparser doesn't provide a function to split a multiline value, right?

**Comment by andreoliwa** [comment]
Hi @FlorianWilhelm, I'm the author of https://github.com/andreoliwa/nitpick/
First: thank you for this package!

> A fix would be to just have the comment within the value and not treating it as a special object. Would that work for you?

Yes, I think that works for me.
`nitpick` doesn't read nor write comments (so far).
It only uses the comment-preserving features of `ConfigUpdater` when creating sections, adding options and changing existing ones.

> could you please test the branch multiline-comment and check if it works for your use-case? If it does I would release a new version 2.0.

I will try this branch on `nitpick` and report back here. 🙂 

---

@thepabloaguilar, thank you again for diving deep into the issue and even contacting @FlorianWilhelm 🙇🏻

**Comment by andreoliwa** [comment]
@FlorianWilhelm The parsing error still happens when I try to update the file.

- Pull request: https://github.com/andreoliwa/nitpick/pull/299
- [Failed build, on the line with the ParsingError](https://github.com/andreoliwa/nitpick/runs/1984544250?check_suite_focus=true#step:6:315)
- [Lines with the traceback; it's failing when I call `update_file()`](https://github.com/andreoliwa/nitpick/runs/1984544250?check_suite_focus=true#step:6:180)
- It seems independent of the Python version: it fails on [3.7](https://github.com/andreoliwa/nitpick/runs/1984544250?check_suite_focus=true#step:6:180) and [also 3.9](https://github.com/andreoliwa/nitpick/runs/1984544469?check_suite_focus=true#step:6:180). It probably fails on other versions, but GitHub fails the workflow fast.

Some info about the installed package:

```
$ poetry show ConfigUpdater
name         : ConfigUpdater
version      : 1.1.3.post17+g73a2c24
description  : Parser like ConfigParser but for updating configuration files

dependencies
 - importlib-metadata *

$ poetry run pip show ConfigUpdater
Name: ConfigUpdater
Version: 1.1.3.post17+g73a2c24
Summary: Parser like ConfigParser but for updating configuration files
Home-page: https://github.com/pyscaffold/configupdater
Author: Florian Wilhelm
Author-email: florian.wilhelm@gmail.com
License: MIT
Location: /Users/aa/Library/Caches/pypoetry/virtualenvs/nitpick-UU_pZ5zs-py3.6/lib/python3.6/site-packages
Requires: importlib-metadata
Required-by: nitpick
```

I hope this is enough info, let me know if you need anything else.
Thanks again!

**Comment by FlorianWilhelm** [comment]
Hi @andreoliwa, thanks for all the information. I think I could pin the bug down to the fact that configupdater was never intended to deal with values that have blank lines (`empty_lines_in_values=True`). Thus in version 1.1.3 `empty_lines_in_values` is always set to false but configparser has it true by default. For this reason, my initial fix worked technically but when doing the final check before updating a file configupdater calls configparser with its own options including `empty_lines_in_values=False`, and then configparser cannot handle comments in multi-line values since they are stripped down to empty lines. 

So here is what I did now. I added `empty_lines_in_values` as a parameter to `ConfigUpdater` and it is `True` by default to reflect the behavior of `ConfigParser`. Thus I had to change the implementation quite a bit since the parser I took from `ConfigParser` has no lookahead and thus I had to add a postprocessing step that merges multi-line values if they were separated by newlines. 

Could you do me a favor and help to test this fix? I guess you have surely a lot of config files to test them with `nitpick`.

**Comment by andreoliwa** [comment]
Hi again @FlorianWilhelm.
Thanks for the changes.
I adapted my code (including `last_block` you have just changed), all is working for me: no more parsing errors are raised.
Whenever you are ready to release a new version, I will use it. 🙂 

---

Nitpick is only parsing `setup.cfg` as a whole, assuming there will be no errors if the file is valid.
It doesn't update items with multiple lines (yet); I might add that feature in the future.

So, for my specific needs, this branch you created is working perfectly.

---

> Could you do me a favor and help to test this fix? I guess you have surely a lot of config files to test them with `nitpick`.

I don't know how to help testing beyond what my code needs.
Nevertheless, I gathered some `setup.cfg` files from projects that use Nitpick, if you want to take a look at them to find possible use cases, to use them in your automated tests:

* [nitpick/setup.cfg at develop · andreoliwa/nitpick](https://github.com/andreoliwa/nitpick/blob/develop/setup.cfg)
* [mimesis-factory/setup.cfg at master · mimesis-lab/mimesis-factory](https://github.com/mimesis-lab/mimesis-factory/blob/master/setup.cfg)
* [returns/setup.cfg at master · dry-python/returns](https://github.com/dry-python/returns/blob/master/setup.cfg)
* [wemake-python-styleguide/setup.cfg at master · wemake-services/wemake-python-styleguide](https://github.com/wemake-services/wemake-python-styleguide/blob/master/setup.cfg)
* [buzzvil-python-styleguide/setup.cfg at master · Buzzvil/buzzvil-python-styleguide](https://github.com/Buzzvil/buzzvil-python-styleguide/blob/master/setup.cfg)
* [wemake-django-template/setup.cfg at master · wemake-services/wemake-django-template](https://github.com/wemake-services/wemake-django-template/blob/master/setup.cfg)
* [dotenv-linter/setup.cfg at master · wemake-services/dotenv-linter](https://github.com/wemake-services/dotenv-linter/blob/master/setup.cfg)

**Comment by FlorianWilhelm** [comment]
Thanks, @andreoliwa for testing, I will release now version 2.0.
