### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by ralphwetzel** [pyscaffold/configupdater#2]
Hi!
I'm trying to use ConfigUpdater.
Just doing `import ConfigUpdater` yet raises a `SyntaxError: invalid syntax` pointing to `*,` at line 546, in Python2 as well as Python3.

<img width="658" alt="image" src="https://user-images.githubusercontent.com/16342003/45183012-276f3880-b223-11e8-824a-8e363d36097e.png">

Any idea what I'm doing wrong and how to fix it?

**Comment by FlorianWilhelm** [comment]
I just added a new release 3.1 which should enforce the usage of Python 3.4 and above.

**Comment by ralphwetzel** [comment]
Hi! Thank you for the link to the PEP.
I indeed did test twice with Python2. Python3(.6) imports without issue.
Perhaps you could indicate a bit more prominentely (e.g. somewhere in the README) that this tool is Python3 only - or make it py2/py3 compatible.

**Comment by FlorianWilhelm** [comment]
@ralphwetzel Since Python 2 reaches end of lifetime in about 1.5 years it makes no sense to put the effort into making a new library PY2/3 compatible. Besides, it also makes the code much harder to read. If you use [PyPI](https://pypi.org/project/configupdater/) to look up configupdater you will see that it says on the left hand side in a structured way that it needs Python 3.4 and above.

**Comment by ralphwetzel** [comment]
That's ok.
Thanks for your effort anyway!
R.
