### ISSUE TITLE
Empty lines in file are not added as Space object

### ISSUE THREAD

**Issue by morcef** [pyscaffold/configupdater#6]
Hi!
Thank you for your ConfigUpdater!

I am having an issue with lines/spaces when reading my .ini file.

"The basic idea of ConfigUpdater is that a configuration file consists of
three kinds of building blocks: sections, comments and spaces for separation."

May I ask, what are lines? Are they only empty lines in comments or key values?

My issue is that when I read my .ini file, the empty lines are not added to the structure as a Space object (as I believe they should). Am I doing something wrong in my example?

`>>>` test = ConfigUpdater()
`>>>` test.read('test.ini')
`>>>` test.structure
[<Section: test>]
`>>>` test.add_section('test2')
`>>>` test.structure
[<Section: test>, <Section: test2>]
`>>>` test['test2'].add_before.space()
<configupdater.configupdater.BlockBuilder object at 0x7fe8f1875668>
`>>>` test.structure
[<Section: test>, <Space>, <Section: test2>]
`>>>` test.update_file()
`>>>` test.read('test.ini')
`>>>` test.structure
[<Section: test>, <Section: test2>]

`~` $ cat test.ini
[test]
key1 = one
key2 = two

[test2]

**Comment by FlorianWilhelm** [comment]
Hi, a line can be anything, it's just some characters or even none which are terminated by a newline `\n`. When parsed a line becomes either a section, a comment, space or an option. 

Regarding your example, when I tried your example I got after `test.add_before.space()` that `structure` looks like `[<Section: test>, <Space>, <Section: test2>]`, so it shows the space. But when you save and read it in again it seems to magically disappear, right? The problem is the ambiguity about the level of a space. There are two levels, the *document level* with sections, comments, and spaces for separation and the *section level* with options, comments, and
spaces. When you parse a file into this hierarchy you might add a space to the document level or the section level. This is what happens here in your example. You add a space to the *document level* and manifest the hierarchy by updating the file. When you parse it again the space is put into the *section level* of `[test]`. You can see that with `test.structure[0].structure`.

You could argue that the space should be put at the *document level* and I agree. This would mean to change some parts of the parser which is right now almost identical to the one in `ConfigParser`. I wanted to keep it that way so that I can incorporate changes in `ConfigParser` also in `ConfigUpdater` easily. For this reason, I chose this tradeoff. If you have a way to add this to the parser without too many changes, I would love to see a PR.

**Comment by morcef** [comment]
Thank you for your quick reply. It made things much clearer, as I have not studied the parser in detail.
It is a fair tradeoff, but if I find it usefull (and worth my time) to try to add this to the parser I will definitly consider a PR :)
Thanks again!

**Comment by FlorianWilhelm** [comment]
I thought about it some more. Maybe one could leave the parser as it is and just make some preprocessing step after the parser has built up the AST in `structure`. One could apply a rule that says that all spaces, within a section, that have no succeeding option are actual document level spaces.  Also, comments at the section level with preceding spaces and no succeeding option should be document level comments, e.g.
```
[test1]
option1 = value
# section-level comment
option2 = value

# document-level comment
[test1]
option3 = value
```
A change like this would definitely need a new major version since it breaks compatibility, so it would be ConfigUpdater 2.0 and some more unit tests. It would be great if you want to work on a PR. I got no time to work myself on it and it fulfills my use-cases anyway right now.

**Comment by morcef** [comment]
Yes, I was thinking something like that, but for now I have only made a quick workaround for my use case. Unfortunately I do not have much time either to work on a major update..
