### ISSUE TITLE
Dependency description for setup.py is not automatically resolvable

### ISSUE THREAD

**Issue by ctheune** [pyscaffold/configupdater#9]
Installing configupdater through pip (e.g. in a virtualenv) doesn't automatically cause a good version of setuptools to be installed but only errors out after installation through pip if setuptools isn't new enough (can happen on older systems and does happen on Travis for me):
https://github.com/pyscaffold/configupdater/blob/e02958e02a3c797508cb2a51c58c91b0fb45885e/setup.py#L16

I'd rather use  setup(..., install_requires=['setuptools>=38.3']) but it looks like the pyscaffold thing is doing something very meta - but apparently that breaks regular installation patterns.

**Comment by FlorianWilhelm** [comment]
`install_requires = setuptools>=38.3` is part of `setup.cfg` which is essentially the same as specifyzing it as `setup(..., install_requires=['setuptools>=38.3'])`. The problem is that pip itself uses `setuptools`. If an old version is used it cannot (or at least in the past, could not) update itself while installing a package. To my understanding, this problem cannot be fixed downstream, especially if one wants to use the newer `setup.cfg` way of defining the parameters instead of the old-school `setup(...)`-call.

**Comment by ctheune** [comment]
Ah, ok. I haven't been up to date on that end I guess. I'll read up on this and see how to deal with that. It is a weird 'meta' situation nevertheless. I guess it means that in a project where you want to use setup.cfg you have to update setuptools early enough. 

<rant>Man. I've been doing setuptools stuff since it was created and we keep running into the same stupid problems since the beginning over and over again.</rant> 

Thanks for explaining!

**Comment by FlorianWilhelm** [comment]
Sure, you are welcome! The building and packaging process still is suboptimal in Python and we have still some way ahead of us. That being said I like the current direction of leaving programmatic configuration as in `setup.py` behind to go for declarative configuration via `setup.cfg` and eventually `pyproject.toml`. But as always in a process of change, things will break...
